default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: nam123

development:
  <<: *default
  database: RealtimeChat_development

test:
  <<: *default
  database: RealtimeChat_test
